title: Jose Quan 
logo: "/images/IMG_7095.JPG?raw=true" 
description: This is a portfolio containing assignments, projects, and presentations. 

   <br><br>
   <a href="https://www.linkedin.com/in/josecquan/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

